### ISSUE TITLE
[BUG] Fix Header component SVG viewBox and path elements after Rust upgrade

### ISSUE THREAD

**Issue by ghanithan** [ghanithan/GitScribe#10]
## Issue Description
After upgrading Rust from 1.77.1 to 1.87.0, the Header component in `src/components/header.rs` has compilation errors related to SVG attribute naming and path element usage.

## Error Details
```
error[E0599]: no function or associated item named `viewBox` found for struct `svg`
  --> src/components/header.rs:28:25
   |
28 |                         viewBox: "0 0 24 24",
   |                        -^^^^^^^ function or associated item not found in `svg`

error[E0574]: expected struct, variant or union type, found built-in attribute `path`
  --> src/components/header.rs:32:29
   |
32 |                       path {
   |                       ^^^^ not a struct, variant or union type
```

## Files Affected
- `src/components/header.rs` (lines 28, 32, 40)

## Required Changes
1. Fix SVG `viewBox` attribute naming (should be `view_box`)
2. Fix path element usage in SVG context
3. Ensure proper SVG element imports and usage
4. Update to current Dioxus SVG API

## Acceptance Criteria
- [ ] Header component compiles without errors
- [ ] SVG attributes use correct naming convention
- [ ] Path elements render correctly
- [ ] Icons display properly in the header
- [ ] No visual regressions

## Priority
🔴 **High** - Blocking compilation

## Labels
- bug
- rust-upgrade
- component
- svg
- compilation-error
