### ISSUE TITLE
[BUG] Fix Button component EventHandler lifetime after Rust upgrade

### ISSUE THREAD

**Issue by ghanithan** [ghanithan/GitScribe#8]
## Issue Description
After upgrading Rust from 1.77.1 to 1.87.0, the Button component in `src/components/button.rs` has compilation errors related to EventHandler lifetime specifiers.

## Error Details
```
error[E0106]: missing lifetime specifier
  --> src/components/button.rs:18:37
   |
18 |     pub onclick: Option<EventHandler<MouseEvent>>,
   |                                     ^ expected named lifetime parameter
```

## Files Affected
- `src/components/button.rs` (line 18)

## Required Changes
1. Fix EventHandler lifetime specifier for the `onclick` prop
2. Update ButtonProps struct to include proper lifetime parameters
3. Ensure compatibility with latest Dioxus version

## Acceptance Criteria
- [ ] Button component compiles without errors
- [ ] EventHandler lifetime is properly specified
- [ ] Component maintains existing functionality
- [ ] No breaking changes to the public API

## Priority
🔴 **High** - Blocking compilation

## Labels
- bug
- rust-upgrade
- component
- compilation-error
