### ISSUE TITLE
[BUG] Fix state management Fermi/Atom API compatibility after Rust upgrade

### ISSUE THREAD

**Issue by ghanithan** [ghanithan/GitScribe#11]
## Issue Description
After upgrading Rust from 1.77.1 to 1.87.0, the state management system in `src/services/state.rs` has compilation errors related to Fermi/Atom API changes.

## Error Details
```
error[E0599]: no function or associated item named `new` found for struct `Atom`
  --> src/services/state.rs:8:46
   |
8 | pub static APP_STATE: Atom<AppState> = Atom::new(AppState::default());
  |                                              ^^^ function or associated item not found in `Atom<_>`

error[E0308]: mismatched types
  --> src/services/state.rs:38:5
   |
36 | pub fn use_app_state(cx: &ScopeState) -> AtomRef<AppState> {
   |                                          ----------------- expected `AtomRef<AppState>`
37 |     let state = use_atom_state(cx, &APP_STATE);
38 |     state
   |     ^^^^^ expected `AtomRef<AppState>`, found `&AtomState<AppState>`

error[E0599]: no method named `get` found for struct `AtomRef`
error[E0599]: no method named `set` found for struct `AtomRef`
```

## Files Affected
- `src/services/state.rs` (lines 8, 36-54)

## Required Changes
1. Update Atom initialization to use current Fermi API
2. Fix AtomRef vs AtomState type mismatches
3. Update state getter/setter methods to current API
4. Ensure compatibility with latest Fermi version
5. Update function signatures and return types

## Acceptance Criteria
- [ ] State management compiles without errors
- [ ] Atom initialization works correctly
- [ ] State getters and setters function properly
- [ ] App state management is preserved
- [ ] No breaking changes to state API

## Priority
🔴 **High** - Blocking compilation

## Labels
- bug
- rust-upgrade
- state-management
- fermi
- compilation-error
