### ISSUE TITLE
[BUG] Fix Home page Button component string type conversions after Rust upgrade

### ISSUE THREAD

**Issue by ghanithan** [ghanithan/GitScribe#12]
## Issue Description
After upgrading Rust from 1.77.1 to 1.87.0, the Home page component in `src/pages/home.rs` has compilation errors related to string type mismatches when passing props to Button components.

## Error Details
```
error[E0308]: mismatched types
  --> src/pages/home.rs:34:32
   |
34 |                         class: "btn-primary"
   |                         -----  ^^^^^^^^^^^^^- help: try using a conversion method: `.to_string()`
   |                         |      |
   |                         |      expected `String`, found `&str`

error[E0308]: mismatched types
  --> src/pages/home.rs:49:32
   |
49 |                         class: "btn-secondary"
   |                         -----  ^^^^^^^^^^^^^^^- help: try using a conversion method: `.to_string()`
   |                         |      |
   |                         |      expected `String`, found `&str`
```

## Files Affected
- `src/pages/home.rs` (lines 34, 49)

## Required Changes
1. Convert string literals to String type for Button class props
2. Update all Button component usages to use proper string types
3. Ensure consistency across all component prop types
4. Consider updating Button component to accept &str if appropriate

## Acceptance Criteria
- [ ] Home page compiles without errors
- [ ] Button components receive correct string types
- [ ] No type conversion warnings
- [ ] Buttons render with correct CSS classes
- [ ] No visual regressions on home page

## Priority
🟡 **Medium** - Blocking compilation but straightforward fix

## Labels
- bug
- rust-upgrade
- component
- type-conversion
- compilation-error
