### ISSUE TITLE
[BUG] Fix ThemeProvider Element lifetime and UseRef API after Rust upgrade

### ISSUE THREAD

**Issue by ghanithan** [ghanithan/GitScribe#9]
## Issue Description
After upgrading Rust from 1.77.1 to 1.87.0, the ThemeProvider component in `src/utils/theme.rs` has compilation errors related to Element lifetime specifiers and UseRef API changes.

## Error Details
```
error[E0106]: missing lifetime specifier
  --> src/utils/theme.rs:28:43
   |
28 | pub fn ThemeProvider(cx: Scope, children: Element) -> Element {
   |                                           ^^^^^^^ expected named lifetime parameter

error[E0599]: no function or associated item named `new` found for struct `dioxus::prelude::UseRef`
  --> src/utils/theme.rs:41:41
   |
41 |     use_context_provider(cx, || UseRef::new(ThemeState::default()))
   |                                         ^^^ function or associated item not found in `UseRef<_>`
```

## Files Affected
- `src/utils/theme.rs` (lines 28, 41)

## Required Changes
1. Fix Element lifetime specifier in ThemeProvider function signature
2. Update UseRef::new to the correct API for the current Dioxus version
3. Ensure proper lifetime management for theme context

## Acceptance Criteria
- [ ] ThemeProvider component compiles without errors
- [ ] Element lifetime is properly specified
- [ ] UseRef is initialized correctly
- [ ] Theme context functionality is preserved
- [ ] No breaking changes to theme API

## Priority
🔴 **High** - Blocking compilation

## Labels
- bug
- rust-upgrade
- theme
- compilation-error
